### ISSUE TITLE
想实现类似telegram一样的消息合并，正好MUKAPP大佬的MSpring-Theme有相应的功能，但是自己鼓捣了一会，总是失败，大佬您能否给改一下啊🤣🤣

### ISSUE THREAD

**Issue by Sunsh4j** [PRO-2684/Scriptio-user-scripts#1]
消息合并的实现代码在 renderer.js文件里，地址是：https://github.com/MUKAPP/LiteLoaderQQNT-MSpring-Theme/blob/v3/renderer.js
如果您感兴趣的话，麻烦给实现一下🤣🤣

**Comment by PRO-2684** [comment]
你也可以参考 LiteTools 的实现，貌似简单一点

https://github.com/xiyuesaves/LiteLoaderQQNT-lite_tools/blob/v3/src/renderer.js#L265

**Comment by Sunsh4j** [comment]
> 你也可以参考 LiteTools 的实现，貌似简单一点
> 
> https://github.com/xiyuesaves/LiteLoaderQQNT-lite_tools/blob/v3/src/renderer.js#L265

OK，多谢大佬
