### ISSUE TITLE
Ctrl+Click 问题 (头像的 Ctrl Click 事件无响应)

### ISSUE THREAD

**Issue by huyeovo** [PRO-2684/Scriptio-user-scripts#12]
inspecio Ctrl+Click 可复制如何实现 我control+点击没能复制

**Comment by PRO-2684** [comment]
当鼠标悬浮时能看到提示的时候，Ctrl Click 可复制提示内容

**Comment by huyeovo** [comment]
<img width="599" alt="image" src="https://github.com/user-attachments/assets/b67f1a39-53d5-465f-8713-918973bb6859">
e 没效果

**Comment by huyeovo** [comment]
Mac

**Comment by huyeovo** [comment]
<img width="206" alt="image" src="https://github.com/user-attachments/assets/4efd05be-3568-4d63-a1da-33a6b41e174e">
会这样

**Comment by PRO-2684** [comment]
> <img alt="image" width="206" src="https://private-user-images.githubusercontent.com/123952524/351146184-4efd05be-3568-4d63-a1da-33a6b41e174e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE4MTI0MDAsIm5iZiI6MTcyMTgxMjEwMCwicGF0aCI6Ii8xMjM5NTI1MjQvMzUxMTQ2MTg0LTRlZmQwNWJlLTM1NjgtNGQ2My1hMWRhLTMzYTZiNDFlMTc0ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyNFQwOTA4MjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wNjI2MDg1YTY1YzdiYmI0NTNhZWVhNzEwNjdmMzFjM2UzMGMyNzZhYmUzZjcxYzI4ZDE3NDNjY2EwYzM5MWNjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.AxX9kSaiqifhNbz1OVVJt402MW3mrsjgMn7jBa-QJlY"> 会这样

在图片上 Ctrl+Click 是否生效？

**Comment by PRO-2684** [comment]
> <img alt="image" width="599" src="https://private-user-images.githubusercontent.com/123952524/351144740-b67f1a39-53d5-465f-8713-918973bb6859.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE4MTI0MDAsIm5iZiI6MTcyMTgxMjEwMCwicGF0aCI6Ii8xMjM5NTI1MjQvMzUxMTQ0NzQwLWI2N2YxYTM5LTUzZDUtNDY1Zi04NzEzLTkxODk3M2JiNjg1OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyNFQwOTA4MjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kM2RlNjI2ODZjODMxNmRlNWViNjk2ZmM5MjExODBjNjU5MzIyMmMyZGIxZmY3NGM3YWFlMzUwODBkMWZiNzVjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.14af0E9MIJrFDKpKuS4QVpG8koxZrV67Mb7OCehrPOw"> e 没效果

这个不是此脚本生成的提示，自然不行。

**Comment by huyeovo** [comment]
hook-vue是失效了嘛
那我怎么用这个 这个好像需要hookvue

**Comment by huyeovo** [comment]
轻量工具箱和他有冲突吗

**Comment by huyeovo** [comment]
![QQ_1721979211995](https://github.com/user-attachments/assets/2147a34e-ee8f-48a2-9a1f-73c2eda7cea6)
我command+点击就这样




我control+点击就这样
![QQ_1721979250627](https://github.com/user-attachments/assets/0a28a17c-5a3c-440b-a11c-bf29f107419c)

**Comment by huyeovo** [comment]
shift+点击可以用 就这个ctrl不行 我看代码里没提示在哪里
![QQ_1721980432560](https://github.com/user-attachments/assets/8d77242f-4876-4982-bab8-7a09c3fde8e1)

**Comment by huyeovo** [comment]
https://github.com/PRO-2684/Scriptio-user-scripts/issues/12#issuecomment-2252150305
鼠标无法停留在这上面

**Comment by huyeovo** [comment]
1080 x 2403, 1.29 MB
6BC360843D3852B822B2CFF7A5097FEB.jpg
https://gchat.qpic.cn/download?appid=1407&fileid=CgoyNDY2OTk0MzU0EhSlrUZDjM44ZmzFdObxgIJ_IyuODRjyt1Ig_wook7WUypPChwNQgL2jAQ&spec=0图片可以，就是头像不行 头像只能显示昵称和qq，赞个数那些在哪里看啊

**Comment by huyeovo** [comment]
1080 x 2403, 1.29 MB
6BC360843D3852B822B2CFF7A5097FEB.jpg
https://gchat.qpic.cn/download?appid=1407&fileid=CgoyNDY2OTk0MzU0EhSlrUZDjM44ZmzFdObxgIJ_IyuODRjyt1Ig_wook7WUypPChwNQgL2jAQ&spec=0

图片可以，就是头像不行 头像只能显示昵称和qq，

**Comment by PRO-2684** [comment]
> 1080 x 2403, 1.29 MB
6BC360843D3852B822B2CFF7A5097FEB.jpg
https://gchat.qpic.cn/download?appid=1407&fileid=CgoyNDY2OTk0MzU0EhSlrUZDjM44ZmzFdObxgIJ_IyuODRjyt1Ig_wook7WUypPChwNQgL2jAQ&spec=0
> 
> 图片可以，就是头像不行 头像只能显示昵称和qq，

头像无法复制提示信息猜测是 QQ 内部逻辑导致的问题

**Comment by PRO-2684** [comment]
经检查，是代码内某处没有做好处理，已在 b0bcbe5906424650bf4fa93562f287f749c09a64 修复。由于是 dev 分支，需要等到 LiteLoader 发版后才会正式发布。若此修复对您意义重大，可自行按照此 commit 修改：将 `avatar.title = tip;` 改为 `setTip(avatar, tip);`。
