### ISSUE TITLE
一言加载失败

### ISSUE THREAD

**Issue by huyeovo** [PRO-2684/Scriptio-user-scripts#13]
![QQ20240723-031103](https://github.com/user-attachments/assets/b41b8e79-a836-4a81-b20e-db3affb2487c)
一言加载失败

**Comment by PRO-2684** [comment]
api 限额了，关闭脚本后等待一段时间即可

**Comment by huyeovo** [comment]
如何解决 还是一直会出现加载失败

**Comment by PRO-2684** [comment]
> 如何解决 还是一直会出现加载失败

浏览器打开 `https://v1.hitokoto.cn/` 查看是否返回了数据
