### ISSUE TITLE
msg-record-enhance问题

### ISSUE THREAD

**Issue by huyeovo** [PRO-2684/Scriptio-user-scripts#14]
![QQ_1721983930906](https://github.com/user-attachments/assets/26160d72-b397-4c1d-b09c-837ce042bb2e)
转发聊天聊天中显示qq为0x

**Comment by PRO-2684** [comment]
以前服务器会返回 QQ 号，但是后来修了此问题。现在服务器不再下发 QQ 号，只给你一个 ID 用于获取头像
