### ISSUE TITLE
1.4.0更新后 hook vue 相关脚本无效

### ISSUE THREAD

**Issue by huyeovo** [PRO-2684/Scriptio-user-scripts#16]
[inspectio](https://github.com/PRO-2684/Scriptio-user-scripts/#inspectio)
nspectio脚本和或其他脚本出现无效问题（应该是插件更新后问题

**Comment by PRO-2684** [comment]
> [inspectio](https://github.com/PRO-2684/Scriptio-user-scripts/#inspectio) nspectio脚本和或其他脚本出现无效问题（应该是插件更新后问题

得使用新版本 liteloader

**Comment by huyeovo** [comment]
依旧不起作用

**Comment by huyeovo** [comment]
鼠标放头像上不弹东西出来了

**Comment by huyeovo** [comment]
是hook Vue (Deprecated)已弃用的原因吗

**Comment by PRO-2684** [comment]
确认 Scriptio, LiteLoader 以及脚本为最新版，删掉 hook_vue.js 后看看

**Comment by huyeovo** [comment]
![QQ_1722430165824](https://github.com/user-attachments/assets/1f5d1c09-b220-4f97-8228-cbe94a98e63b)
![QQ_1722430179777](https://github.com/user-attachments/assets/fa2e1079-a731-4a10-80cb-a871e1f8829f)
依旧不行

**Comment by huyeovo** [comment]
![QQ_1722430220387](https://github.com/user-attachments/assets/efd8bbb8-2fc9-442c-8801-0550d1ac0b8e)

**Comment by huyeovo** [comment]
不行啊
？

**Comment by PRO-2684** [comment]
禁用其它插件，特别是工具箱（已知暂未适配新版 LiteLoader）
