### ISSUE TITLE
show-time不太好使

### ISSUE THREAD

**Issue by MRUIAW** [PRO-2684/Scriptio-user-scripts#3]
![image](https://github.com/PRO-2684/Scriptio-user-scripts/assets/119018519/4d44143d-6461-4b66-8176-24fef22e14dd)
如图, 切换聊天窗口/上下滚动消息, 重启QQ后依然无效.
(嘴笨, issue也不太熟该怎么写, 要是我语气看起来很差的话sry)

**Comment by PRO-2684** [comment]
已知装了轻量工具箱和 LLAPI 会导致冲突，因为都需要 hook vue

**Comment by MRUIAW** [comment]
明白了, 感谢

**Comment by MRUIAW** [comment]
啊对了, msg-record-enhance用不了也是同样的原因是吗

**Comment by PRO-2684** [comment]
> 啊对了, msg-record-enhance用不了也是同样的原因是吗

是的，目前正在联系开发者，如果统一一下实现方式应该可以做到兼容
