### ISSUE TITLE
请问关于自定义快捷键

### ISSUE THREAD

**Issue by Elflare** [PRO-2684/Scriptio-user-scripts#4]
1. 我想在shortcutio.js基础上加点功能，实现老版qq的Ctrl+12345等切换到第12345个聊天窗口（暂时先不说新版ctrl+12是切换页面，快捷键可以换），或者ctrl+tab向下切换，ctrl+shift+tab向上切换（新版是ctrl+↑，ctrl+↓，这需要两只手，按起来不方便）。
2. 尝试用click方法：viewport_list = document.querySelector(".viewport-list__inner").click();
3. 发现能获取到对象，但click没反应。求指教

**Comment by PRO-2684** [comment]
用 `mousedown` Event 即可，例如点击第一个聊天窗口：

```javascript
function click(ele) {
    const evt = new MouseEvent("mousedown");
    ele.dispatchEvent(evt);
}
click(document.querySelector(".viewport-list__inner")?.firstElementChild);
```

**Comment by Elflare** [comment]
> 用 `mousedown` Event 即可，例如点击第一个聊天窗口：
> 
> ```js
> function click(ele) {
>     const evt = new MouseEvent("mousedown");
>     ele.dispatchEvent(evt);
> }
> click(document.querySelector(".viewport-list__inner")?.firstElementChild);
> ```

感谢大佬
