### ISSUE TITLE
hook-vue如何使用LLAPI或轻量工具箱提供的hook-vue方法

### ISSUE THREAD

**Issue by KagaJiankui** [PRO-2684/Scriptio-user-scripts#5]
试图让依赖hook-vue.js的脚本兼容LLAPI和/或轻量工具箱, 我没有前端知识, 但阅读代码发现几个插件的hook代码都较为相似. 请问大佬有没有什么方法能让用到hook-vue的Scriptio脚本和轻量工具箱/llapi兼容?

**Comment by PRO-2684** [comment]
主要区别在此脚本定义了 `__VUE_MOUNT__` 和 `__VUE_UNMOUNT__` 两个变量，以便其他脚本添加函数。可以尝试把其他插件的相应代码用此脚本代替。

**Comment by KagaJiankui** [comment]
lite_tools作者已兼容
