### ISSUE TITLE
link-preview 遇到下载链接会下载……

### ISSUE THREAD

**Issue by MapleRecall** [PRO-2684/Scriptio-user-scripts#6]
hover到一个下载地址上直接开始全速下载……最好先发个HEAD请求判断下content-length

**Comment by PRO-2684** [comment]
很多网站不支持通过 HEAD 获取 `Content-Length`，所以这个方法通配性不是很好。通过 `Content-Type` 筛选掉不是文本的链接应该可行。

**Comment by PRO-2684** [comment]
> 很多网站不支持通过 HEAD 获取 `Content-Length`，所以这个方法通配性不是很好。通过 `Content-Type` 筛选掉不是文本的链接应该可行。

ci 版的 scriptio.fetchText 支持通过 HEAD 判断是否为文本，可以试试有没有问题

**Comment by PRO-2684** [comment]
工具箱已有完整功能的链接预览
