### ISSUE TITLE
link-preview支持Night-stars-1/LiteLoaderQQNT-Plugin-QQPromote的样式和缓存功能

### ISSUE THREAD

**Issue by KagaJiankui** [PRO-2684/Scriptio-user-scripts#7]
有无可能将[Night-stars-1/LiteLoaderQQNT-Plugin-QQPromote](https://github.com/Night-stars-1/LiteLoaderQQNT-Plugin-QQPromote)的链接预览代码和样式移植到用户脚本? 或者在link-preview脚本中实现类似的缓存功能和hover样式?

样式如下图所示:
![image](https://github.com/PRO-2684/Scriptio-user-scripts/assets/58453886/c895a414-b089-4408-be33-c40bcc627383)

**Comment by PRO-2684** [comment]
完全实现此功能对我来说过于困难，若有人愿意做出来我很欢迎 PR

**Comment by KagaJiankui** [comment]
简单实现的话, 可以在悬浮窗中加入favicon和缩略图显示(主要是b站视频封面的缩略图)

**Comment by PRO-2684** [comment]
工具箱已有完整功能的链接预览
