### ISSUE TITLE
inspectio.js在最新版不生效

### ISSUE THREAD

**Issue by LuorixDev** [PRO-2684/Scriptio-user-scripts#8]
inspectio.js在最新版不生效

**Comment by PRO-2684** [comment]
我并未更新到最新版，目前无法测试
之后可能会适配最新版

**Comment by LuorixDev** [comment]
感谢，qq增强删库了大家能用的只有这个了😂

**Comment by PRO-2684** [comment]
> 感谢，qq增强删库了大家能用的只有这个了😂

具体是想要 inspectio 的什么功能呢
[工具箱](https://github.com/xiyuesaves/LiteLoaderQQNT-lite_tools) 更新更加频繁，可以去试试看，我是比较养老的人

**Comment by LuorixDev** [comment]
**qq号查看**这些功能
之前有一个插件**qq增强**删库了，有很多有意思的功能都没了
其中有一个可以在**群**里面显示发送者qq号和昵称备注（**好友的昵称**非群昵称）
![image](https://github.com/PRO-2684/Scriptio-user-scripts/assets/157946924/85c85827-25d8-47aa-94e2-f202dc49f09c)
那个撤回的插件最近也用不了哩

**Comment by LuorixDev** [comment]
重启qq后似乎是可以用的
